TRADUCTIONS = {
    "titre": {"fr": "KATARENGA&CO.", "en": "KATARENGA&CO."},
    "parametres": {"fr": "PARAMÈTRES", "en": "SETTINGS"},
    "volume_effets": {"fr": "Volume effets", "en": "Sound effects"},
    "volume_musique": {"fr": "Volume musique", "en": "Music volume"},
    "retour": {"fr": "Retour", "en": "Back"},
    "langue_changee": {"fr": "Langue changée : {lang}", "en": "Language changed: {lang}"},
    "langue": {"fr": "Langue", "en": "Language"},
    "langue_fr": {"fr": "FR", "en": "FR"},
    "langue_en": {"fr": "EN", "en": "EN"},
    "jouer_katarenga": {"fr": "KATARANGA", "en": "KATARANGA"},
    "jouer_congress": {"fr": "CONGRESS", "en": "CONGRESS"},
    "jouer_isolation": {"fr": "ISOLATION", "en": "ISOLATION"},
    "mode_1v1": {"fr": "1 VS 1", "en": "1 VS 1"},
    "mode_ia": {"fr": "IA", "en": "AI"},
    "go": {"fr": "JOUER", "en": "PLAY"},
    "aide": {"fr": "Aide", "en": "Help"},
    "aide_texte": {"fr": "Choisissez un mode :\n- 1 VS 1 : deux joueurs humains\n- IA : vous contre un adversaire aléatoire", "en": "Choose a mode:\n- 1 VS 1: two human players\n- AI: you against a random opponent"},
    "choisir_mode": {"fr": "Choisir le mode", "en": "Choose Mode"},
    "jouer_local_ou_online": {"fr": "Jouer en local ou en ligne ?", "en": "Play locally or online?"},
    "local": {"fr": "Local", "en": "Local"},
    "reseau": {"fr": "Réseau", "en": "Network"},
    "mode_onligne": {"fr": "Mode en ligne", "en": "Online Mode"},
    "host_or_join": {"fr": "Héberger ou rejoindre une partie ?", "en": "Host or join a game?"},
    "host": {"fr": "Héberger", "en": "Host"},
    "server_started_waiting": {"fr": "Serveur démarré !", "en": "Server started !"},
    "join": {"fr": "Rejoindre", "en": "Join"},
    "connected_to_server": {"fr": "Connecté au serveur !", "en": "Connected to server!"},
    "connection_failed": {"fr": "Échec de la connexion.", "en": "Connection failed."},
    "client_connected_from": {"fr": "Client connecté depuis {addr}", "en": "Client connected from {addr}"},
    "received_from": {"fr": "Reçu de {addr} : {msg}", "en": "Received from {addr}: {msg}"},
    "client_disconnected": {"fr": "Client {addr} déconnecté", "en": "Client {addr} disconnected"},
    "plateau": {"fr": "Plateau :", "en": "Board:"},
    "plateau_auto": {"fr": "Généré automatiquement", "en": "Automatically generated"},
    "plateau_perso": {"fr": "Quadrants personnalisés", "en": "Custom quadrants"},
    "waiting_for_client": {"fr": "En attente qu'un joueur rejoigne la partie...", "en": "Waiting for a player to join the game..."},
    "enter_server_ip": {"fr": "Adresse IP du serveur à rejoindre", "en": "Server IP address to join"},
    "rafraichir": {"fr": "Rafraîchir", "en": "Refresh"},
    "attente_joueur": {"fr": "En attente d'un joueur...", "en": "Waiting for a player..."},
}