""""
    Dictionary text
"""

TRANSLATIONS = {
    "title": {"fr": "KATARENGA&CO.", "en": "KATARENGA&CO."},
    "settings": {"fr": "PARAMÈTRES", "en": "SETTINGS"},
    "sound_effects_volume": {"fr": "Volume effets", "en": "Sound effects"},
    "music_volume": {"fr": "Volume musique", "en": "Music volume"},
    "back": {"fr": "Retour", "en": "Back"},
    "language_changed": {"fr": "Langue changée : {lang}", "en": "Language changed: {lang}"},
    "language": {"fr": "Langue", "en": "Language"},
    "language_fr": {"fr": "FR", "en": "FR"},
    "language_en": {"fr": "EN", "en": "EN"},
    "play_katarenga": {"fr": "KATARENGA", "en": "KATARENGA"},
    "play_congress": {"fr": "CONGRESS", "en": "CONGRESS"},
    "play_isolation": {"fr": "ISOLATION", "en": "ISOLATION"},
    "mode_1v1": {"fr": "1 VS 1", "en": "1 VS 1"},
    "mode_ai": {"fr": "IA", "en": "AI"},
    "play": {"fr": "Jouer", "en": "Play"},
    "help": {"fr": "Aide", "en": "Help"},
    "white": {"fr": "Blanc", "en": "White"},
    "black": {"fr": "Noir", "en": "Black"},
    "help_text": {"fr": "Choisissez un mode :\n- 1 VS 1 : deux joueurs humains\n- IA : vous contre un adversaire aléatoire", "en": "Choose a mode:\n- 1 VS 1: two human players\n- AI: you against a random opponent"},
    "choose_mode": {"fr": "Choisir le mode", "en": "Choose Mode"},
    "play_local_or_online": {"fr": "Jouer en local ou en ligne ?", "en": "Play locally or online?"},
    "local": {"fr": "Local", "en": "Local"},
    "online_mode": {"fr": "Mode en ligne", "en": "Online Mode"},
    "host_or_join": {"fr": "Héberger ou rejoindre une partie ?", "en": "Host or join a game?"},
    "host": {"fr": "Héberger", "en": "Host"},
    "server_started_waiting": {"fr": "Serveur démarré !", "en": "Server started !"},
    "join": {"fr": "Rejoindre", "en": "Join"},
    "connected_to_server": {"fr": "Connecté au serveur !", "en": "Connected to server!"},
    "connection_failed": {"fr": "Échec de la connexion.", "en": "Connection failed."},
    "client_connected_from": {"fr": "Client connecté depuis {addr}", "en": "Client connected from {addr}"},
    "received_from": {"fr": "Reçu de {addr} : {msg}", "en": "Received from {addr}: {msg}"},
    "client_disconnected": {"fr": "Client {addr} déconnecté", "en": "Client {addr} disconnected"},
    "board": {"fr": "Configuration du plateau :", "en": "Configuration of the board:"},
    "auto_board": {"fr": "Généré automatiquement", "en": "Automatically generated"},
    "custom_quadrants": {"fr": "Quadrants personnalisés", "en": "Custom quadrants"},
    "waiting_for_client": {"fr": "En attente qu'un joueur rejoigne la partie...", "en": "Waiting for a player to join the game..."},
    "enter_server_ip": {"fr": "Adresse IP du serveur à rejoindre", "en": "Server IP address to join"},
    "refresh": {"fr": "Rafraîchir", "en": "Refresh"},
    "choose_game_mode": {"fr": "Choisissez le mode de jeu", "en": "Choose game mode"},
    "solo_mode": {"fr": "Solo", "en": "Solo"},
    "network_mode": {"fr": "Réseau", "en": "Network"},
    "available_servers": {"fr": "Serveurs disponibles:", "en": "Available servers:"},
    "host_or_join_2": {"fr": "Héberger ou rejoindre ?", "en": "Host or join?"},
    "heberger": {"fr": "Héberger", "en": "Host"},
    "join_server": {"fr": "Rejoindre un serveur", "en": "Join a server"},
    "enter_server_name": {"fr": "Entrez le nom du serveur", "en": "Enter server name"},
    "waiting_for_player": {"fr": "En attente d'un joueur...", "en": "Waiting for a player..."},
    "server_created": {"fr": "Serveur créé !", "en": "Server created!"},
    "ip": {"fr": "IP", "en": "IP"},
    "server_name": {"fr": "Nom du serveur", "en": "Server name"},
    "client_connected": {"fr": "Un joueur a rejoint la partie !", "en": "A player has joined the game!"},
    "connecting_to": {"fr": "Connexion à", "en": "Connecting to"},
    "connected": {"fr": "Connexion réussie !", "en": "Connected!"},
    "game_mode": {"fr": "Mode de jeu", "en": "Game Mode"},
    "enter_player_name": {"fr": "Entrez votre nom de joueur", "en": "Enter your player name"},
    "server_stopped": {"fr": "Serveur arrêté", "en": "Server stopped"},
    "welcome_to_portal": {"fr": "Bienvenue dans le portail d'accueil du jeu !", "en": "Welcome to the game portal!"},
    "enter_username": {"fr": "Entrez votre nom d'utilisateur pour vous amuser :", "en": "Enter your username to have fun:"},
    "enter_portal": {"fr": "Entrez dans le portail", "en": "Enter the portal"},
    "modes_subtitle": {"fr": "Faites votre choix parmi les modes de jeux passionnants ci-dessous.", "en": "Make your choice among the exciting game modes below."},
    "choose_your_game_mode": {"fr": "Choisissez votre mode de jeu", "en": "Choose your game mode"},
    "welcome": {"fr": "Bienvenue", "en": "Welcome"},
    "play": {"fr": "Jouer", "en": "Play"},
    "katarenga_mode": {"fr": "Katarenga", "en": "Katarenga"},
    "congress_mode": {"fr": "Congress", "en": "Congress"},
    "isolation_mode": {"fr": "Isolation", "en": "Isolation"},
    "katarenga_description": {"fr": "Un mode de jeu inspiré du shogi et des échecs.", "en": "A game mode inspired by shogi and chess."},
    "congress_description": {"fr": "Un mode de réflexion où chaque coup compte.", "en": "A thinking mode where every move counts."},
    "isolation_description": {"fr": "Un mode duel tactique pour isoler l'adversaire.", "en": "A tactical duel mode to isolate your opponent."},
    "logout": {"fr": "Se déconnecter", "en": "Logout"},
    "game_configuration": {"fr": "Configuration du jeu", "en": "Game configuration"},
    "generated_board": {"fr": "Plateau généré", "en": "Generated board"},
    "create_4x4_quadrant": {"fr": "Créer un Quadrant 4x4", "en": "Create a 4x4 Quadrant"},
    "save_quadrant": {"fr": "Sauvegarder Quadrant", "en": "Save Quadrant"},
    "new_quadrant": {"fr": "Nouveau Quadrant", "en": "New Quadrant"},
    "play_with_these_quadrants": {"fr": "Jouer avec ces Quadrants", "en": "Play with these Quadrants"},
    "about": {"fr": "À propos", "en": "About"},
    "credits": {"fr": "Crédits", "en": "Credits"},
    "close": {"fr": "Fermer", "en": "Close"},
    "about_text": {
        "fr": "Smart Games.\nProjet B1",
        "en": "Smart Games.\nProject B1"
    },
    "credits_text": {
        "fr": "Développé par:\n Ibtihel BOUGUERN\n Malak CHEHAM\n Yasmine BENAMIR",
        "en": "Developed by:\n Ibtihel BOUGUERN\n Malak CHEHAM\n Yasmine BENAMIR"
    },
    "network_host_mode": {"fr": "Réseau (Hôte)", "en": "Network (Host)"},
    "network_client_mode": {"fr": "Réseau (Client)", "en": "Network (Client)"},
    "turn_of": {"fr": "Tour de", "en": "Turn of"},
    "remaining_pawns": {"fr": "Pions Restants", "en": "Remaining Pawns"},
    "incomplete": {"fr": "Incomplet", "en": "Incomplete"},
    "all_squares_must_be_colored": {"fr": "Toutes les cases doivent être colorées.", "en": "All squares must be colored."},
    "four_quadrants_ready": {"fr": "Les 4 quadrants sont prêts. Cliquez sur 'Jouer avec ces quadrants'.", "en": "The 4 quadrants are ready. Click on 'Play with these quadrants'."},
    "quadrant_num": {"fr": "Quadrant {num}/4", "en": "Quadrant {num}/4"},
    "move_to_other_player_failed": {"fr": "Échec de l'envoi du coup à l'autre joueur", "en": "Failed to send move to other player"},
    "victory": {"fr": "Victoire!", "en": "Victory!"},
    "victory_2_pawns_in_corners": {"fr": "{nom} a gagné : 2 pions dans les coins adverses.", "en": "{nom} won: 2 pawns in the opponent's corners."},
    "victory_white_not_enough_pawns": {"fr": "{nom} a gagné : Blanc n'a plus assez de pions.", "en": "{nom} won: White does not have enough pawns."},
    "victory_black_not_enough_pawns": {"fr": "{nom} a gagné : Noir n'a plus assez de pions.", "en": "{nom} won: Black does not have enough pawns."},
    "game_rules": {"fr": "Règles du jeu", "en": "Game rules"},
    "katarenga_rules": {"fr": "Règles de Katarenga", "en": "Katarenga rules"},
    "congress_rules": {"fr": "Règles de Congress", "en": "Congress rules"},
    "isolation_rules": {"fr": "Règles d'Isolation", "en": "Isolation rules"},
    "objective": {"fr": "Objectif :", "en": "Objective:"},
    "katarenga_objective_1": {"fr": "Atteindre les deux camps adverses après avoir franchi sa ligne.", "en": "Reach both opponent's camps after crossing your line."},
    "katarenga_objective_2": {"fr": "Capturer les pions adverses pour l'empêcher.", "en": "Capture opponent's pawns to prevent them."},
    "move_according_to_color": {"fr": "Déplacement selon la couleur :", "en": "Move according to color:"},
    "blue_king": {"fr": "Bleu : Roi (1 case toutes directions)", "en": "Blue: King (1 square any direction)"},
    "green_knight": {"fr": "Vert : Cavalier (en L)", "en": "Green: Knight (L-shape)"},
    "yellow_bishop": {"fr": "Jaune : Fou (diagonale, arrêt sur première case jaune)", "en": "Yellow: Bishop (diagonal, stops on first yellow)"},
    "red_rook": {"fr": "Rouge : Tour (ligne/colonne, arrêt sur première case rouge)", "en": "Red: Rook (row/column, stops on first red)"},
    "captures": {"fr": "Captures :", "en": "Captures:"},
    "captures_from_2nd_turn": {"fr": "Possibles à partir du 2e tour.", "en": "Possible from 2nd turn."},
    "captured_pawns_removed": {"fr": "Les pions capturés sont retirés du jeu.", "en": "Captured pawns are removed from the game."},
    "congress_objective_1": {"fr": "Rassembler tous vos pions en un seul bloc connexe (orthogonal).", "en": "Gather all your pawns in a single orthogonally connected block."},
    "move": {"fr": "Déplacement :", "en": "Move:"},
    "congress_move": {"fr": "Identique à Katarenga, selon la couleur de la case.", "en": "Same as Katarenga, according to the color of the square."},
    "no_capture_allowed": {"fr": "Pas de capture autorisée:", "en": "No capture allowed:"},
    "pawns_cannot_overlap": {"fr": "Les pions ne peuvent pas se superposer.", "en": "Pawns cannot overlap."},
    "first_to_connect_wins": {"fr": "Le premier joueur à connecter tous ses pions gagne.", "en": "First player to connect all pawns wins."},
    "isolation_objective_1": {"fr": "Être le dernier à pouvoir poser un pion.", "en": "Be the last to place a pawn."},
    "how_to_play": {"fr": "Déroulement :", "en": "How to play:"},
    "isolation_how_to_play_1": {"fr": "Chaque joueur place un pion à tour de rôle.", "en": "Each player places a pawn in turn."},
    "isolation_how_to_play_2": {"fr": "Un pion ne peut pas être placé sur une case en prise.", "en": "A pawn cannot be placed on a threatened square."},
    "threatened": {"fr": "En prise :", "en": "Threatened:"},
    "threatened_definition": {"fr": "Une case est en prise si un pion adverse pourrait y aller selon sa couleur.", "en": "A square is threatened if an opponent's pawn could reach it according to its color."},
    "no_capture_no_movement": {"fr": "Pas de capture, pas de déplacement : uniquement la pose de pions.", "en": "No capture, no movement: only pawn placement."},
    "no_rules_available": {"fr": "Aucune règle disponible pour ce jeu.", "en": "No rules available for this game."},
    "square_already_occupied": {"fr": "Cette case est déjà occupée.", "en": "This square is already occupied."},
    "square_blocked": {"fr": "La case est bloquée par un pion déjà posé.", "en": "The square is blocked by an already placed pawn."},
    "player": {"fr": "Joueur", "en": "Player"},
    "won": {"fr": "a gagné", "en": "won"},
}